/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.mdsd.packettracer.text


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GridDslRuntimeModule extends AbstractGridDslRuntimeModule {
}
