/*
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.mdsd.packettracer.text


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GridDslStandaloneSetup extends GridDslStandaloneSetupGenerated {

	def static void doSetup() {
		new GridDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
