/**
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.mdsd.packettracer.text.validation;

import hu.bme.mit.mdsd.packettracer.text.validation.AbstractGridDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GridDslValidator extends AbstractGridDslValidator {
}
