/**
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.mdsd.packettracer.text;

import hu.bme.mit.mdsd.packettracer.text.AbstractGridDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GridDslRuntimeModule extends AbstractGridDslRuntimeModule {
}
