/**
 * generated by Xtext 2.12.0
 */
package hu.bme.mit.mdsd.packettracer.text;

import hu.bme.mit.mdsd.packettracer.text.GridDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GridDslStandaloneSetup extends GridDslStandaloneSetupGenerated {
  public static void doSetup() {
    new GridDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
